// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEuprcXGMptSaR3FVtIp8W8Xb1cDBXahs',
    appId: '1:984843371341:web:0c5727cebd84f8eeacad04',
    messagingSenderId: '984843371341',
    projectId: 'chatapp-619e6',
    authDomain: 'chatapp-619e6.firebaseapp.com',
    storageBucket: 'chatapp-619e6.firebasestorage.app',
    measurementId: 'G-ENC5NJ9C4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm4B06FBpnpQx1rQlB8RixnRgBvr38xPs',
    appId: '1:984843371341:android:5d99e61d24adb2eeacad04',
    messagingSenderId: '984843371341',
    projectId: 'chatapp-619e6',
    storageBucket: 'chatapp-619e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrDgyNdzN3HQg828FKIRZjPhtMifTofPw',
    appId: '1:984843371341:ios:413642deb9d00fd4acad04',
    messagingSenderId: '984843371341',
    projectId: 'chatapp-619e6',
    storageBucket: 'chatapp-619e6.firebasestorage.app',
    iosBundleId: 'com.mychatapp.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEuprcXGMptSaR3FVtIp8W8Xb1cDBXahs',
    appId: '1:984843371341:web:2aaddb7c00a1e836acad04',
    messagingSenderId: '984843371341',
    projectId: 'chatapp-619e6',
    authDomain: 'chatapp-619e6.firebaseapp.com',
    storageBucket: 'chatapp-619e6.firebasestorage.app',
    measurementId: 'G-ET5V8F4BEV',
  );

}